// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwV6F32a0MlsxhazH0qnl07hqcDTQO_yA',
    appId: '1:63646434248:web:185e623b9835687ccdb6fd',
    messagingSenderId: '63646434248',
    projectId: 'fantasyastra-3a1ad',
    authDomain: 'fantasyastra-3a1ad.firebaseapp.com',
    storageBucket: 'fantasyastra-3a1ad.firebasestorage.app',
    measurementId: 'G-TBQBWH68X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysl6QtK0-aZi6uYFIIaUu-snIi4gKCdI',
    appId: '1:63646434248:android:1d51269ea6c77ccfcdb6fd',
    messagingSenderId: '63646434248',
    projectId: 'fantasyastra-3a1ad',
    storageBucket: 'fantasyastra-3a1ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtTI1PfuIIeI8HHftfIpMUGk1xihDc_d4',
    appId: '1:63646434248:ios:9c99473616fc013fcdb6fd',
    messagingSenderId: '63646434248',
    projectId: 'fantasyastra-3a1ad',
    storageBucket: 'fantasyastra-3a1ad.firebasestorage.app',
    iosBundleId: 'com.fantasyastra.deep.fantasyastra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtTI1PfuIIeI8HHftfIpMUGk1xihDc_d4',
    appId: '1:63646434248:ios:9c99473616fc013fcdb6fd',
    messagingSenderId: '63646434248',
    projectId: 'fantasyastra-3a1ad',
    storageBucket: 'fantasyastra-3a1ad.firebasestorage.app',
    iosBundleId: 'com.fantasyastra.deep.fantasyastra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwV6F32a0MlsxhazH0qnl07hqcDTQO_yA',
    appId: '1:63646434248:web:a9f6d7d98eebb64ccdb6fd',
    messagingSenderId: '63646434248',
    projectId: 'fantasyastra-3a1ad',
    authDomain: 'fantasyastra-3a1ad.firebaseapp.com',
    storageBucket: 'fantasyastra-3a1ad.firebasestorage.app',
    measurementId: 'G-KKSLYDB3TX',
  );

}